# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_client(object):
    def setupUi(self, client):
        client.setObjectName("client")
        client.resize(703, 476)
        self.sendTextEdit = QtWidgets.QTextEdit(client)
        self.sendTextEdit.setGeometry(QtCore.QRect(30, 30, 331, 411))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.sendTextEdit.setFont(font)
        self.sendTextEdit.setObjectName("sendTextEdit")
        self.sendFileButton = QtWidgets.QPushButton(client)
        self.sendFileButton.setGeometry(QtCore.QRect(500, 30, 111, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.sendFileButton.setFont(font)
        self.sendFileButton.setObjectName("sendFileButton")
        self.SendTextButton = QtWidgets.QPushButton(client)
        self.SendTextButton.setGeometry(QtCore.QRect(390, 30, 101, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.SendTextButton.setFont(font)
        self.SendTextButton.setObjectName("SendTextButton")
        self.serverACKLabel = QtWidgets.QLabel(client)
        self.serverACKLabel.setGeometry(QtCore.QRect(390, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.serverACKLabel.setFont(font)
        self.serverACKLabel.setObjectName("serverACKLabel")
        self.exitButton = QtWidgets.QPushButton(client)
        self.exitButton.setGeometry(QtCore.QRect(620, 30, 51, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.serverACKEdit = QtWidgets.QTextEdit(client)
        self.serverACKEdit.setGeometry(QtCore.QRect(390, 140, 281, 301))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.serverACKEdit.setFont(font)
        self.serverACKEdit.setObjectName("serverACKEdit")
        self.ReconnectButton = QtWidgets.QPushButton(client)
        self.ReconnectButton.setGeometry(QtCore.QRect(620, 80, 51, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ReconnectButton.setFont(font)
        self.ReconnectButton.setObjectName("ReconnectButton")

        self.retranslateUi(client)
        QtCore.QMetaObject.connectSlotsByName(client)

    def retranslateUi(self, client):
        _translate = QtCore.QCoreApplication.translate
        client.setWindowTitle(_translate("client", "客户端"))
        self.sendTextEdit.setHtml(_translate("client", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">请输入要发送的文本：</p></body></html>"))
        self.sendFileButton.setText(_translate("client", "选择文件发送"))
        self.SendTextButton.setText(_translate("client", "文本发送"))
        self.serverACKLabel.setText(_translate("client", "服务器确认信息"))
        self.exitButton.setText(_translate("client", "退出"))
        self.ReconnectButton.setText(_translate("client", "重连"))
